### ISSUE TITLE
Large audio files usable with this project?

### ISSUE THREAD

**Issue by ck-gd** [kaveenkumar/Speech_Recognition_and_Emotion_Detection_in_English_and_German#1]
Hi,

thanks for bringing this project to live.

I would like to process an audio file that is longer than one hour with this project to perform a text-to-speech recognition.

Is this possible with this project?

Thanks in advance!

**Comment by kaveenkumar** [comment]
Hi,

I haven't tried to transcribe a file longer than one hour.

On the model level, processing a long file should not be a problem. Only problem could be that the application might crash because of the size (but again I haven't trialed it). Feel free to check it out :)
