### ISSUE TITLE
Google Drive link contains files of less than 1 MByte of data in total

### ISSUE THREAD

**Issue by ck-gd** [kaveenkumar/Speech_Recognition_and_Emotion_Detection_in_English_and_German#2]
Hi,

I recently tried to download the files from https://drive.google.com/drive/folders/1wuhkZ3b5jKfoNIDfaEzrdg-KZVagk-lS?usp=sharing

It seems to me that some files are missing. The overall download size of the zip file is ~250 kByte.

The files that I get are:
```
tree -h
.
└── [4.0K]  Transcriber
    ├── [4.0K]  audio
    │   ├── [4.0K]  english
    │   │   └── [ 91K]  LDC93S1_pcms16le_1_16000.wav
    │   └── [4.0K]  german
    │       ├── [105K]  common_voice_de_17284683.wav
    │       └── [120K]  common_voice_de_17284698.wav
    └── [4.0K]  models
        ├── [4.0K]  english
        │   └── [ 329]  alphabet.txt
        └── [4.0K]  german
            └── [  79]  alphabet.txt

7 directories, 5 files
```

Could you perhaps help me with this issue?

Thanks in advance.

**Comment by kaveenkumar** [comment]
Hi, thanks for writing.

By mistake I had deleted the model files from my GDrive to free up some space :D
I have now re-uploaded the model files. Could you please check?

Cheers!

**Comment by ck-gd** [comment]
Hi, 

thanks!

I have been able to retrieve it completely.

If it is concerning _me_, you can again free up some space :-)
